using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

[Preserve]
public sealed partial class C_DbPartitionVertical : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4853283651170602758UL,5979098809253003430UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public List<C_DbPartitionVerticalMetas> F_DbPartitionVerticalMetas => BGCodeGenUtils.GetNested<C_DbPartitionVerticalMetas>(_F_DbPartitionVerticalMetas, Index);
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4665918244331616929UL, 11193224049255317390UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_F_DbPartitionVerticalMetas;
	public static BansheeGz.BGDatabase.BGFieldNested _F_DbPartitionVerticalMetas => _ufle12jhs77_F_DbPartitionVerticalMetas ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(5476295703566318609UL, 12539318734117378232UL), () => _ufle12jhs77_F_DbPartitionVerticalMetas = null);
	private C_DbPartitionVertical() : base(MetaDefault) {}
	private C_DbPartitionVertical(BGId id) : base(MetaDefault, id) {}
	private C_DbPartitionVertical(BGMetaEntity meta) : base(meta) {}
	private C_DbPartitionVertical(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static C_DbPartitionVertical FindEntity(Predicate<C_DbPartitionVertical> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<C_DbPartitionVertical> FindEntities(Predicate<C_DbPartitionVertical> filter, List<C_DbPartitionVertical> result=null, Comparison<C_DbPartitionVertical> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<C_DbPartitionVertical> action, Predicate<C_DbPartitionVertical> filter=null, Comparison<C_DbPartitionVertical> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static C_DbPartitionVertical GetEntity(BGId entityId) => (C_DbPartitionVertical) MetaDefault.GetEntity(entityId);
	public static C_DbPartitionVertical GetEntity(int index) => (C_DbPartitionVertical) MetaDefault[index];
	public static C_DbPartitionVertical GetEntity(string entityName) => (C_DbPartitionVertical) MetaDefault.GetEntity(entityName);
	public static C_DbPartitionVertical NewEntity() => (C_DbPartitionVertical) MetaDefault.NewEntity();
	public static C_DbPartitionVertical NewEntity(BGId entityId) => (C_DbPartitionVertical) MetaDefault.NewEntity(entityId);
	public static C_DbPartitionVertical NewEntity(Action<C_DbPartitionVertical> callback) => (C_DbPartitionVertical) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((C_DbPartitionVertical)entity)));
	public List<C_DbPartitionVerticalMetas> FillF_DbPartitionVerticalMetas(List<C_DbPartitionVerticalMetas> result) => BGCodeGenUtils.GetNested<C_DbPartitionVerticalMetas>(_F_DbPartitionVerticalMetas, Index, result);
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4853283651170602758UL,5979098809253003430UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4665918244331616929UL, 11193224049255317390UL));
		_ufle12jhs77_F_DbPartitionVerticalMetas = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(_metaDefault, new BGId(5476295703566318609UL, 12539318734117378232UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_DbPartitionVerticalMetas = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new C_DbPartitionVertical(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new C_DbPartitionVertical(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "DbPartitionVertical";
		public const string name = "name";
		public const string DbPartitionVerticalMetas = "DbPartitionVerticalMetas";
	}
}

[Preserve]
public sealed partial class C_DbPartitionVerticalMetas : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(4726024332363597461UL,16507830069143585174UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public C_DbPartitionVertical F_DbPartitionVertical
	{
		get => (C_DbPartitionVertical) _F_DbPartitionVertical[Index];
		set => _F_DbPartitionVertical[Index] = value;
	}
	public BansheeGz.BGDatabase.BGMetaEntity F_metaRef
	{
		get => _F_metaRef[Index];
		set => _F_metaRef[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5271285092506593270UL, 15515926821749735334UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_F_DbPartitionVertical;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _F_DbPartitionVertical => _ufle12jhs77_F_DbPartitionVertical ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5098258687173573775UL, 12489646567721377695UL), () => _ufle12jhs77_F_DbPartitionVertical = null);
	private static BansheeGz.BGDatabase.BGFieldPartitionMetaReference _ufle12jhs77_F_metaRef;
	public static BansheeGz.BGDatabase.BGFieldPartitionMetaReference _F_metaRef => _ufle12jhs77_F_metaRef ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldPartitionMetaReference>(MetaDefault, new BGId(4651457453234173454UL, 7381830247663075474UL), () => _ufle12jhs77_F_metaRef = null);
	private C_DbPartitionVerticalMetas() : base(MetaDefault) {}
	private C_DbPartitionVerticalMetas(BGId id) : base(MetaDefault, id) {}
	private C_DbPartitionVerticalMetas(BGMetaEntity meta) : base(meta) {}
	private C_DbPartitionVerticalMetas(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static C_DbPartitionVerticalMetas FindEntity(Predicate<C_DbPartitionVerticalMetas> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<C_DbPartitionVerticalMetas> FindEntities(Predicate<C_DbPartitionVerticalMetas> filter, List<C_DbPartitionVerticalMetas> result=null, Comparison<C_DbPartitionVerticalMetas> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<C_DbPartitionVerticalMetas> action, Predicate<C_DbPartitionVerticalMetas> filter=null, Comparison<C_DbPartitionVerticalMetas> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static C_DbPartitionVerticalMetas GetEntity(BGId entityId) => (C_DbPartitionVerticalMetas) MetaDefault.GetEntity(entityId);
	public static C_DbPartitionVerticalMetas GetEntity(int index) => (C_DbPartitionVerticalMetas) MetaDefault[index];
	public static C_DbPartitionVerticalMetas GetEntity(string entityName) => (C_DbPartitionVerticalMetas) MetaDefault.GetEntity(entityName);
	public static C_DbPartitionVerticalMetas NewEntity() => (C_DbPartitionVerticalMetas) MetaDefault.NewEntity();
	public static C_DbPartitionVerticalMetas NewEntity(BGId entityId) => (C_DbPartitionVerticalMetas) MetaDefault.NewEntity(entityId);
	public static C_DbPartitionVerticalMetas NewEntity(Action<C_DbPartitionVerticalMetas> callback) => (C_DbPartitionVerticalMetas) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((C_DbPartitionVerticalMetas)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(4726024332363597461UL,16507830069143585174UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5271285092506593270UL, 15515926821749735334UL));
		_ufle12jhs77_F_DbPartitionVertical = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5098258687173573775UL, 12489646567721377695UL));
		_ufle12jhs77_F_metaRef = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldPartitionMetaReference>(_metaDefault, new BGId(4651457453234173454UL, 7381830247663075474UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_DbPartitionVertical = null;
		_ufle12jhs77_F_metaRef = null;
	}
	public static C_DbPartitionVerticalMetas NewEntity(C_DbPartitionVertical owner) => (C_DbPartitionVerticalMetas) MetaDefault.NewEntity(owner);
	public static C_DbPartitionVerticalMetas NewEntity(C_DbPartitionVertical owner, BGId entityId) => (C_DbPartitionVerticalMetas) MetaDefault.NewEntity(owner, entityId);
	public static C_DbPartitionVerticalMetas NewEntity(C_DbPartitionVertical owner, Action<C_DbPartitionVerticalMetas> callback) => (C_DbPartitionVerticalMetas) MetaDefault.NewEntity(owner, new BGMetaEntity.NewEntityContext(entity => callback((C_DbPartitionVerticalMetas)entity)));

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new C_DbPartitionVerticalMetas(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new C_DbPartitionVerticalMetas(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "DbPartitionVerticalMetas";
		public const string name = "name";
		public const string DbPartitionVertical = "DbPartitionVertical";
		public const string metaRef = "metaRef";
	}
}

[Preserve]
public sealed partial class C_M_Item : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4933297127591480799UL,6390849319240722820UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public System.String F_nameKey
	{
		get => _F_nameKey[Index];
		set => _F_nameKey[Index] = value;
	}
	public System.String F_iconAddrKey
	{
		get => _F_iconAddrKey[Index];
		set => _F_iconAddrKey[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5319455835436388461UL, 14335400216294370703UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_nameKey;
	public static BansheeGz.BGDatabase.BGFieldString _F_nameKey => _ufle12jhs77_F_nameKey ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4631420013838560950UL, 4954029888602698912UL), () => _ufle12jhs77_F_nameKey = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_iconAddrKey;
	public static BansheeGz.BGDatabase.BGFieldString _F_iconAddrKey => _ufle12jhs77_F_iconAddrKey ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5705235272951314303UL, 12216613049049960886UL), () => _ufle12jhs77_F_iconAddrKey = null);
	private C_M_Item() : base(MetaDefault) {}
	private C_M_Item(BGId id) : base(MetaDefault, id) {}
	private C_M_Item(BGMetaEntity meta) : base(meta) {}
	private C_M_Item(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static C_M_Item FindEntity(Predicate<C_M_Item> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<C_M_Item> FindEntities(Predicate<C_M_Item> filter, List<C_M_Item> result=null, Comparison<C_M_Item> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<C_M_Item> action, Predicate<C_M_Item> filter=null, Comparison<C_M_Item> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static C_M_Item GetEntity(BGId entityId) => (C_M_Item) MetaDefault.GetEntity(entityId);
	public static C_M_Item GetEntity(int index) => (C_M_Item) MetaDefault[index];
	public static C_M_Item GetEntity(string entityName) => (C_M_Item) MetaDefault.GetEntity(entityName);
	public static C_M_Item NewEntity() => (C_M_Item) MetaDefault.NewEntity();
	public static C_M_Item NewEntity(BGId entityId) => (C_M_Item) MetaDefault.NewEntity(entityId);
	public static C_M_Item NewEntity(Action<C_M_Item> callback) => (C_M_Item) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((C_M_Item)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4933297127591480799UL,6390849319240722820UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5319455835436388461UL, 14335400216294370703UL));
		_ufle12jhs77_F_nameKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4631420013838560950UL, 4954029888602698912UL));
		_ufle12jhs77_F_iconAddrKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5705235272951314303UL, 12216613049049960886UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_nameKey = null;
		_ufle12jhs77_F_iconAddrKey = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new C_M_Item(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new C_M_Item(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "M_Item";
		public const string name = "name";
		public const string nameKey = "nameKey";
		public const string iconAddrKey = "iconAddrKey";
	}
}

[Preserve]
public sealed partial class C_P_MapUpgrade : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5221336876434674571UL,9903781968383590036UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public C_M_Map F_map
	{
		get => (C_M_Map) _F_map[Index];
		set => _F_map[Index] = value;
	}
	public System.Int32 F_maxCount
	{
		get => _F_maxCount[Index];
		set => _F_maxCount.SetValue(this, value);
	}
	public System.Int32 F_currentCount
	{
		get => _F_currentCount[Index];
		set => _F_currentCount.SetValue(this, value);
	}
	public System.Boolean F_isOpen
	{
		get => _F_isOpen[Index];
		set => _F_isOpen.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5462398807156247872UL, 10628600243689735341UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_F_map;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _F_map => _ufle12jhs77_F_map ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5584599143751686650UL, 11208637826587807399UL), () => _ufle12jhs77_F_map = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_F_maxCount;
	public static BansheeGz.BGDatabase.BGFieldInt _F_maxCount => _ufle12jhs77_F_maxCount ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5409584399723337171UL, 17788157176798624146UL), () => _ufle12jhs77_F_maxCount = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_F_currentCount;
	public static BansheeGz.BGDatabase.BGFieldInt _F_currentCount => _ufle12jhs77_F_currentCount ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5086575861708999167UL, 12889930845982722468UL), () => _ufle12jhs77_F_currentCount = null);
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_F_isOpen;
	public static BansheeGz.BGDatabase.BGFieldBool _F_isOpen => _ufle12jhs77_F_isOpen ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5398836876151179975UL, 8826750865618482567UL), () => _ufle12jhs77_F_isOpen = null);
	private C_P_MapUpgrade() : base(MetaDefault) {}
	private C_P_MapUpgrade(BGId id) : base(MetaDefault, id) {}
	private C_P_MapUpgrade(BGMetaEntity meta) : base(meta) {}
	private C_P_MapUpgrade(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static C_P_MapUpgrade FindEntity(Predicate<C_P_MapUpgrade> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<C_P_MapUpgrade> FindEntities(Predicate<C_P_MapUpgrade> filter, List<C_P_MapUpgrade> result=null, Comparison<C_P_MapUpgrade> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<C_P_MapUpgrade> action, Predicate<C_P_MapUpgrade> filter=null, Comparison<C_P_MapUpgrade> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static C_P_MapUpgrade GetEntity(BGId entityId) => (C_P_MapUpgrade) MetaDefault.GetEntity(entityId);
	public static C_P_MapUpgrade GetEntity(int index) => (C_P_MapUpgrade) MetaDefault[index];
	public static C_P_MapUpgrade GetEntity(string entityName) => (C_P_MapUpgrade) MetaDefault.GetEntity(entityName);
	public static C_P_MapUpgrade NewEntity() => (C_P_MapUpgrade) MetaDefault.NewEntity();
	public static C_P_MapUpgrade NewEntity(BGId entityId) => (C_P_MapUpgrade) MetaDefault.NewEntity(entityId);
	public static C_P_MapUpgrade NewEntity(Action<C_P_MapUpgrade> callback) => (C_P_MapUpgrade) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((C_P_MapUpgrade)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5221336876434674571UL,9903781968383590036UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5462398807156247872UL, 10628600243689735341UL));
		_ufle12jhs77_F_map = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5584599143751686650UL, 11208637826587807399UL));
		_ufle12jhs77_F_maxCount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5409584399723337171UL, 17788157176798624146UL));
		_ufle12jhs77_F_currentCount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5086575861708999167UL, 12889930845982722468UL));
		_ufle12jhs77_F_isOpen = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(_metaDefault, new BGId(5398836876151179975UL, 8826750865618482567UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_map = null;
		_ufle12jhs77_F_maxCount = null;
		_ufle12jhs77_F_currentCount = null;
		_ufle12jhs77_F_isOpen = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new C_P_MapUpgrade(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new C_P_MapUpgrade(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "P_MapUpgrade";
		public const string name = "name";
		public const string map = "map";
		public const string maxCount = "maxCount";
		public const string currentCount = "currentCount";
		public const string isOpen = "isOpen";
	}
}

[Preserve]
public sealed partial class C_E_Event : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4705184771535386746UL,2130726293677765276UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4719694000007802588UL, 15965745727070308277UL), () => _ufle12jhs77_F_name = null);
	private C_E_Event() : base(MetaDefault) {}
	private C_E_Event(BGId id) : base(MetaDefault, id) {}
	private C_E_Event(BGMetaEntity meta) : base(meta) {}
	private C_E_Event(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static C_E_Event FindEntity(Predicate<C_E_Event> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<C_E_Event> FindEntities(Predicate<C_E_Event> filter, List<C_E_Event> result=null, Comparison<C_E_Event> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<C_E_Event> action, Predicate<C_E_Event> filter=null, Comparison<C_E_Event> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static C_E_Event GetEntity(BGId entityId) => (C_E_Event) MetaDefault.GetEntity(entityId);
	public static C_E_Event GetEntity(int index) => (C_E_Event) MetaDefault[index];
	public static C_E_Event GetEntity(string entityName) => (C_E_Event) MetaDefault.GetEntity(entityName);
	public static C_E_Event NewEntity() => (C_E_Event) MetaDefault.NewEntity();
	public static C_E_Event NewEntity(BGId entityId) => (C_E_Event) MetaDefault.NewEntity(entityId);
	public static C_E_Event NewEntity(Action<C_E_Event> callback) => (C_E_Event) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((C_E_Event)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4705184771535386746UL,2130726293677765276UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4719694000007802588UL, 15965745727070308277UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new C_E_Event(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new C_E_Event(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "E_Event";
		public const string name = "name";
	}
}

[Preserve]
public sealed partial class C_M_Addressables : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5409628843007120488UL,15233289140864123276UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public System.String F_addrKey
	{
		get => _F_addrKey[Index];
		set => _F_addrKey[Index] = value;
	}
	public AddressablesType F_type
	{
		get => (AddressablesType) _F_type.GetStoredValue(Index);
		set => _F_type.SetStoredValue(Index, (System.Int32) value);
	}
	public System.String F_desc
	{
		get => _F_desc[Index];
		set => _F_desc[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5028683615260684844UL, 16745311772861670301UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_addrKey;
	public static BansheeGz.BGDatabase.BGFieldString _F_addrKey => _ufle12jhs77_F_addrKey ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5292223705511683934UL, 7436525132849971103UL), () => _ufle12jhs77_F_addrKey = null);
	private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_F_type;
	public static BansheeGz.BGDatabase.BGFieldEnum _F_type => _ufle12jhs77_F_type ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(MetaDefault, new BGId(4665268914636405058UL, 4521366268816376467UL), () => _ufle12jhs77_F_type = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_desc;
	public static BansheeGz.BGDatabase.BGFieldString _F_desc => _ufle12jhs77_F_desc ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5101181131987347114UL, 4209021793282690490UL), () => _ufle12jhs77_F_desc = null);
	private C_M_Addressables() : base(MetaDefault) {}
	private C_M_Addressables(BGId id) : base(MetaDefault, id) {}
	private C_M_Addressables(BGMetaEntity meta) : base(meta) {}
	private C_M_Addressables(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static C_M_Addressables FindEntity(Predicate<C_M_Addressables> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<C_M_Addressables> FindEntities(Predicate<C_M_Addressables> filter, List<C_M_Addressables> result=null, Comparison<C_M_Addressables> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<C_M_Addressables> action, Predicate<C_M_Addressables> filter=null, Comparison<C_M_Addressables> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static C_M_Addressables GetEntity(BGId entityId) => (C_M_Addressables) MetaDefault.GetEntity(entityId);
	public static C_M_Addressables GetEntity(int index) => (C_M_Addressables) MetaDefault[index];
	public static C_M_Addressables GetEntity(string entityName) => (C_M_Addressables) MetaDefault.GetEntity(entityName);
	public static C_M_Addressables NewEntity() => (C_M_Addressables) MetaDefault.NewEntity();
	public static C_M_Addressables NewEntity(BGId entityId) => (C_M_Addressables) MetaDefault.NewEntity(entityId);
	public static C_M_Addressables NewEntity(Action<C_M_Addressables> callback) => (C_M_Addressables) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((C_M_Addressables)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5409628843007120488UL,15233289140864123276UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5028683615260684844UL, 16745311772861670301UL));
		_ufle12jhs77_F_addrKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5292223705511683934UL, 7436525132849971103UL));
		_ufle12jhs77_F_type = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(_metaDefault, new BGId(4665268914636405058UL, 4521366268816376467UL));
		_ufle12jhs77_F_desc = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5101181131987347114UL, 4209021793282690490UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_addrKey = null;
		_ufle12jhs77_F_type = null;
		_ufle12jhs77_F_desc = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new C_M_Addressables(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new C_M_Addressables(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "M_Addressables";
		public const string name = "name";
		public const string addrKey = "addrKey";
		public const string type = "type";
		public const string desc = "desc";
	}
}

[Preserve]
public sealed partial class C_LOC_Texts : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5147745031998890996UL,14238959348634087847UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public System.String F_key
	{
		get => _F_key[Index];
		set => _F_key[Index] = value;
	}
	public System.String F_ko
	{
		get => _F_ko[Index];
		set => _F_ko[Index] = value;
	}
	public System.String F_en
	{
		get => _F_en[Index];
		set => _F_en[Index] = value;
	}
	public System.String F_jp
	{
		get => _F_jp[Index];
		set => _F_jp[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5524248013094644915UL, 13960004835482704305UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_key;
	public static BansheeGz.BGDatabase.BGFieldString _F_key => _ufle12jhs77_F_key ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5016962598249769529UL, 267684822604163211UL), () => _ufle12jhs77_F_key = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_ko;
	public static BansheeGz.BGDatabase.BGFieldString _F_ko => _ufle12jhs77_F_ko ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5493278917907199212UL, 1263742247487996607UL), () => _ufle12jhs77_F_ko = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_en;
	public static BansheeGz.BGDatabase.BGFieldString _F_en => _ufle12jhs77_F_en ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5555008530882078298UL, 7257286900481836478UL), () => _ufle12jhs77_F_en = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_jp;
	public static BansheeGz.BGDatabase.BGFieldString _F_jp => _ufle12jhs77_F_jp ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4732666979764799235UL, 11990424466712198053UL), () => _ufle12jhs77_F_jp = null);
	private C_LOC_Texts() : base(MetaDefault) {}
	private C_LOC_Texts(BGId id) : base(MetaDefault, id) {}
	private C_LOC_Texts(BGMetaEntity meta) : base(meta) {}
	private C_LOC_Texts(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static C_LOC_Texts FindEntity(Predicate<C_LOC_Texts> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<C_LOC_Texts> FindEntities(Predicate<C_LOC_Texts> filter, List<C_LOC_Texts> result=null, Comparison<C_LOC_Texts> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<C_LOC_Texts> action, Predicate<C_LOC_Texts> filter=null, Comparison<C_LOC_Texts> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static C_LOC_Texts GetEntity(BGId entityId) => (C_LOC_Texts) MetaDefault.GetEntity(entityId);
	public static C_LOC_Texts GetEntity(int index) => (C_LOC_Texts) MetaDefault[index];
	public static C_LOC_Texts GetEntity(string entityName) => (C_LOC_Texts) MetaDefault.GetEntity(entityName);
	public static C_LOC_Texts NewEntity() => (C_LOC_Texts) MetaDefault.NewEntity();
	public static C_LOC_Texts NewEntity(BGId entityId) => (C_LOC_Texts) MetaDefault.NewEntity(entityId);
	public static C_LOC_Texts NewEntity(Action<C_LOC_Texts> callback) => (C_LOC_Texts) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((C_LOC_Texts)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5147745031998890996UL,14238959348634087847UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5524248013094644915UL, 13960004835482704305UL));
		_ufle12jhs77_F_key = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5016962598249769529UL, 267684822604163211UL));
		_ufle12jhs77_F_ko = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5493278917907199212UL, 1263742247487996607UL));
		_ufle12jhs77_F_en = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5555008530882078298UL, 7257286900481836478UL));
		_ufle12jhs77_F_jp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4732666979764799235UL, 11990424466712198053UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_key = null;
		_ufle12jhs77_F_ko = null;
		_ufle12jhs77_F_en = null;
		_ufle12jhs77_F_jp = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new C_LOC_Texts(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new C_LOC_Texts(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "LOC_Texts";
		public const string name = "name";
		public const string key = "key";
		public const string ko = "ko";
		public const string en = "en";
		public const string jp = "jp";
	}
}

[Preserve]
public sealed partial class C_M_Currency : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4620956991943587508UL,5373875214812990096UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public System.String F_nameKey
	{
		get => _F_nameKey[Index];
		set => _F_nameKey[Index] = value;
	}
	public System.String F_iconAddrKey
	{
		get => _F_iconAddrKey[Index];
		set => _F_iconAddrKey[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5299225749181478151UL, 17342421149086560917UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_nameKey;
	public static BansheeGz.BGDatabase.BGFieldString _F_nameKey => _ufle12jhs77_F_nameKey ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5646712081174135408UL, 18327330165664235395UL), () => _ufle12jhs77_F_nameKey = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_iconAddrKey;
	public static BansheeGz.BGDatabase.BGFieldString _F_iconAddrKey => _ufle12jhs77_F_iconAddrKey ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4864807472861924395UL, 3750330014466161041UL), () => _ufle12jhs77_F_iconAddrKey = null);
	private C_M_Currency() : base(MetaDefault) {}
	private C_M_Currency(BGId id) : base(MetaDefault, id) {}
	private C_M_Currency(BGMetaEntity meta) : base(meta) {}
	private C_M_Currency(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static C_M_Currency FindEntity(Predicate<C_M_Currency> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<C_M_Currency> FindEntities(Predicate<C_M_Currency> filter, List<C_M_Currency> result=null, Comparison<C_M_Currency> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<C_M_Currency> action, Predicate<C_M_Currency> filter=null, Comparison<C_M_Currency> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static C_M_Currency GetEntity(BGId entityId) => (C_M_Currency) MetaDefault.GetEntity(entityId);
	public static C_M_Currency GetEntity(int index) => (C_M_Currency) MetaDefault[index];
	public static C_M_Currency GetEntity(string entityName) => (C_M_Currency) MetaDefault.GetEntity(entityName);
	public static C_M_Currency NewEntity() => (C_M_Currency) MetaDefault.NewEntity();
	public static C_M_Currency NewEntity(BGId entityId) => (C_M_Currency) MetaDefault.NewEntity(entityId);
	public static C_M_Currency NewEntity(Action<C_M_Currency> callback) => (C_M_Currency) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((C_M_Currency)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4620956991943587508UL,5373875214812990096UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5299225749181478151UL, 17342421149086560917UL));
		_ufle12jhs77_F_nameKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5646712081174135408UL, 18327330165664235395UL));
		_ufle12jhs77_F_iconAddrKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4864807472861924395UL, 3750330014466161041UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_nameKey = null;
		_ufle12jhs77_F_iconAddrKey = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new C_M_Currency(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new C_M_Currency(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "M_Currency";
		public const string name = "name";
		public const string nameKey = "nameKey";
		public const string iconAddrKey = "iconAddrKey";
	}
}

[Preserve]
public sealed partial class C_M_Map : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5757518179423953646UL,16157399547299418777UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public System.String F_nameKey
	{
		get => _F_nameKey[Index];
		set => _F_nameKey[Index] = value;
	}
	public System.String F_iconAddrKey
	{
		get => _F_iconAddrKey[Index];
		set => _F_iconAddrKey[Index] = value;
	}
	public List<C_M_Map> F_ParentMap
	{
		get => BGCodeGenUtils.MultipleRelationGet<C_M_Map>(_F_ParentMap, Index);
		set => BGCodeGenUtils.MultipleRelationSet<C_M_Map>(_F_ParentMap, Index, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5170874591336506155UL, 11106913501708283273UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_nameKey;
	public static BansheeGz.BGDatabase.BGFieldString _F_nameKey => _ufle12jhs77_F_nameKey ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4729206966446849177UL, 17425482992811695017UL), () => _ufle12jhs77_F_nameKey = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_iconAddrKey;
	public static BansheeGz.BGDatabase.BGFieldString _F_iconAddrKey => _ufle12jhs77_F_iconAddrKey ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4975028386842148826UL, 11787988675291282311UL), () => _ufle12jhs77_F_iconAddrKey = null);
	private static BansheeGz.BGDatabase.BGFieldRelationMultiple _ufle12jhs77_F_ParentMap;
	public static BansheeGz.BGDatabase.BGFieldRelationMultiple _F_ParentMap => _ufle12jhs77_F_ParentMap ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationMultiple>(MetaDefault, new BGId(4674979770218121172UL, 5593737195120833700UL), () => _ufle12jhs77_F_ParentMap = null);
	public List<C_P_MapUpgrade> RelatedP_MapUpgradeListUsingmapRelation => BGCodeGenUtils.GetRelatedInbound<C_P_MapUpgrade>(C_P_MapUpgrade._F_map, Id);
	public List<C_M_Map> RelatedM_MapListUsingParentMapRelation => BGCodeGenUtils.GetRelatedInbound<C_M_Map>(C_M_Map._F_ParentMap, Id);
	private C_M_Map() : base(MetaDefault) {}
	private C_M_Map(BGId id) : base(MetaDefault, id) {}
	private C_M_Map(BGMetaEntity meta) : base(meta) {}
	private C_M_Map(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static C_M_Map FindEntity(Predicate<C_M_Map> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<C_M_Map> FindEntities(Predicate<C_M_Map> filter, List<C_M_Map> result=null, Comparison<C_M_Map> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<C_M_Map> action, Predicate<C_M_Map> filter=null, Comparison<C_M_Map> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static C_M_Map GetEntity(BGId entityId) => (C_M_Map) MetaDefault.GetEntity(entityId);
	public static C_M_Map GetEntity(int index) => (C_M_Map) MetaDefault[index];
	public static C_M_Map GetEntity(string entityName) => (C_M_Map) MetaDefault.GetEntity(entityName);
	public static C_M_Map NewEntity() => (C_M_Map) MetaDefault.NewEntity();
	public static C_M_Map NewEntity(BGId entityId) => (C_M_Map) MetaDefault.NewEntity(entityId);
	public static C_M_Map NewEntity(Action<C_M_Map> callback) => (C_M_Map) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((C_M_Map)entity)));
	public void F_ParentMap_Add(C_M_Map related) => BGCodeGenUtils.MultipleRelationAdd(_F_ParentMap, Index, related);
	public void F_ParentMap_Remove(C_M_Map related) => BGCodeGenUtils.MultipleRelationRemove(_F_ParentMap, Index, related);
	public List<C_P_MapUpgrade> FillRelatedP_MapUpgradeListUsingmapRelation(List<C_P_MapUpgrade> result) => BGCodeGenUtils.GetRelatedInbound<C_P_MapUpgrade>(C_P_MapUpgrade._F_map, Id, result);
	public List<C_M_Map> FillRelatedM_MapListUsingParentMapRelation(List<C_M_Map> result) => BGCodeGenUtils.GetRelatedInbound<C_M_Map>(C_M_Map._F_ParentMap, Id, result);
	public List<C_M_Map> FillF_ParentMap(List<C_M_Map> result) => BGCodeGenUtils.MultipleRelationGet<C_M_Map>(_F_ParentMap, Index, result);
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5757518179423953646UL,16157399547299418777UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5170874591336506155UL, 11106913501708283273UL));
		_ufle12jhs77_F_nameKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4729206966446849177UL, 17425482992811695017UL));
		_ufle12jhs77_F_iconAddrKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4975028386842148826UL, 11787988675291282311UL));
		_ufle12jhs77_F_ParentMap = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationMultiple>(_metaDefault, new BGId(4674979770218121172UL, 5593737195120833700UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_nameKey = null;
		_ufle12jhs77_F_iconAddrKey = null;
		_ufle12jhs77_F_ParentMap = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new C_M_Map(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new C_M_Map(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "M_Map";
		public const string name = "name";
		public const string nameKey = "nameKey";
		public const string iconAddrKey = "iconAddrKey";
		public const string ParentMap = "ParentMap";
	}
}

[Preserve]
public sealed partial class C_M_Building : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5385766755937559734UL,4611976258184282547UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public System.String F_nameKey
	{
		get => _F_nameKey[Index];
		set => _F_nameKey[Index] = value;
	}
	public System.String F_iconAddrKey
	{
		get => _F_iconAddrKey[Index];
		set => _F_iconAddrKey[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4910537985421187283UL, 5996318884341998269UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_nameKey;
	public static BansheeGz.BGDatabase.BGFieldString _F_nameKey => _ufle12jhs77_F_nameKey ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4832930965109889803UL, 5492232845835243650UL), () => _ufle12jhs77_F_nameKey = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_iconAddrKey;
	public static BansheeGz.BGDatabase.BGFieldString _F_iconAddrKey => _ufle12jhs77_F_iconAddrKey ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5326088520799865729UL, 12396977884734125967UL), () => _ufle12jhs77_F_iconAddrKey = null);
	private C_M_Building() : base(MetaDefault) {}
	private C_M_Building(BGId id) : base(MetaDefault, id) {}
	private C_M_Building(BGMetaEntity meta) : base(meta) {}
	private C_M_Building(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static C_M_Building FindEntity(Predicate<C_M_Building> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<C_M_Building> FindEntities(Predicate<C_M_Building> filter, List<C_M_Building> result=null, Comparison<C_M_Building> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<C_M_Building> action, Predicate<C_M_Building> filter=null, Comparison<C_M_Building> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static C_M_Building GetEntity(BGId entityId) => (C_M_Building) MetaDefault.GetEntity(entityId);
	public static C_M_Building GetEntity(int index) => (C_M_Building) MetaDefault[index];
	public static C_M_Building GetEntity(string entityName) => (C_M_Building) MetaDefault.GetEntity(entityName);
	public static C_M_Building NewEntity() => (C_M_Building) MetaDefault.NewEntity();
	public static C_M_Building NewEntity(BGId entityId) => (C_M_Building) MetaDefault.NewEntity(entityId);
	public static C_M_Building NewEntity(Action<C_M_Building> callback) => (C_M_Building) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((C_M_Building)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5385766755937559734UL,4611976258184282547UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4910537985421187283UL, 5996318884341998269UL));
		_ufle12jhs77_F_nameKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4832930965109889803UL, 5492232845835243650UL));
		_ufle12jhs77_F_iconAddrKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5326088520799865729UL, 12396977884734125967UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_nameKey = null;
		_ufle12jhs77_F_iconAddrKey = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new C_M_Building(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new C_M_Building(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "M_Building";
		public const string name = "name";
		public const string nameKey = "nameKey";
		public const string iconAddrKey = "iconAddrKey";
	}
}

[Preserve]
public sealed partial class C_M_Character : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5329076445405620516UL,15546908995918190980UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public System.String F_nameKey
	{
		get => _F_nameKey[Index];
		set => _F_nameKey[Index] = value;
	}
	public System.String F_iconAddrKey
	{
		get => _F_iconAddrKey[Index];
		set => _F_iconAddrKey[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5758495452879801486UL, 1954738189952396214UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_nameKey;
	public static BansheeGz.BGDatabase.BGFieldString _F_nameKey => _ufle12jhs77_F_nameKey ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5704669516871591792UL, 10190717536045107328UL), () => _ufle12jhs77_F_nameKey = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_iconAddrKey;
	public static BansheeGz.BGDatabase.BGFieldString _F_iconAddrKey => _ufle12jhs77_F_iconAddrKey ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4777511813767696603UL, 8053513385467788213UL), () => _ufle12jhs77_F_iconAddrKey = null);
	public List<C_P_CurrentCharacter> RelatedP_CurrentCharacterListUsingCharacterRelation => BGCodeGenUtils.GetRelatedInbound<C_P_CurrentCharacter>(C_P_CurrentCharacter._F_Character, Id);
	private C_M_Character() : base(MetaDefault) {}
	private C_M_Character(BGId id) : base(MetaDefault, id) {}
	private C_M_Character(BGMetaEntity meta) : base(meta) {}
	private C_M_Character(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static C_M_Character FindEntity(Predicate<C_M_Character> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<C_M_Character> FindEntities(Predicate<C_M_Character> filter, List<C_M_Character> result=null, Comparison<C_M_Character> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<C_M_Character> action, Predicate<C_M_Character> filter=null, Comparison<C_M_Character> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static C_M_Character GetEntity(BGId entityId) => (C_M_Character) MetaDefault.GetEntity(entityId);
	public static C_M_Character GetEntity(int index) => (C_M_Character) MetaDefault[index];
	public static C_M_Character GetEntity(string entityName) => (C_M_Character) MetaDefault.GetEntity(entityName);
	public static C_M_Character NewEntity() => (C_M_Character) MetaDefault.NewEntity();
	public static C_M_Character NewEntity(BGId entityId) => (C_M_Character) MetaDefault.NewEntity(entityId);
	public static C_M_Character NewEntity(Action<C_M_Character> callback) => (C_M_Character) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((C_M_Character)entity)));
	public List<C_P_CurrentCharacter> FillRelatedP_CurrentCharacterListUsingCharacterRelation(List<C_P_CurrentCharacter> result) => BGCodeGenUtils.GetRelatedInbound<C_P_CurrentCharacter>(C_P_CurrentCharacter._F_Character, Id, result);
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5329076445405620516UL,15546908995918190980UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5758495452879801486UL, 1954738189952396214UL));
		_ufle12jhs77_F_nameKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5704669516871591792UL, 10190717536045107328UL));
		_ufle12jhs77_F_iconAddrKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4777511813767696603UL, 8053513385467788213UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_nameKey = null;
		_ufle12jhs77_F_iconAddrKey = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new C_M_Character(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new C_M_Character(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "M_Character";
		public const string name = "name";
		public const string nameKey = "nameKey";
		public const string iconAddrKey = "iconAddrKey";
	}
}

[Preserve]
public sealed partial class C_P_CurrentCharacter : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5650283725877348560UL,2541090741315398062UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public C_M_Character F_Character
	{
		get => (C_M_Character) _F_Character[Index];
		set => _F_Character[Index] = value;
	}
	public System.Int32 F_Level
	{
		get => _F_Level[Index];
		set => _F_Level.SetValue(this, value);
	}
	public System.Int64 F_Exp
	{
		get => _F_Exp[Index];
		set => _F_Exp.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4664195966365923244UL, 1369876315198988210UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_F_Character;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _F_Character => _ufle12jhs77_F_Character ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5641411118652723440UL, 5848902406740597685UL), () => _ufle12jhs77_F_Character = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_F_Level;
	public static BansheeGz.BGDatabase.BGFieldInt _F_Level => _ufle12jhs77_F_Level ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5230488391329767903UL, 13692343905593137327UL), () => _ufle12jhs77_F_Level = null);
	private static BansheeGz.BGDatabase.BGFieldLong _ufle12jhs77_F_Exp;
	public static BansheeGz.BGDatabase.BGFieldLong _F_Exp => _ufle12jhs77_F_Exp ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldLong>(MetaDefault, new BGId(5228304755770654548UL, 6284609355131697283UL), () => _ufle12jhs77_F_Exp = null);
	private C_P_CurrentCharacter() : base(MetaDefault) {}
	private C_P_CurrentCharacter(BGId id) : base(MetaDefault, id) {}
	private C_P_CurrentCharacter(BGMetaEntity meta) : base(meta) {}
	private C_P_CurrentCharacter(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static C_P_CurrentCharacter FindEntity(Predicate<C_P_CurrentCharacter> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<C_P_CurrentCharacter> FindEntities(Predicate<C_P_CurrentCharacter> filter, List<C_P_CurrentCharacter> result=null, Comparison<C_P_CurrentCharacter> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<C_P_CurrentCharacter> action, Predicate<C_P_CurrentCharacter> filter=null, Comparison<C_P_CurrentCharacter> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static C_P_CurrentCharacter GetEntity(BGId entityId) => (C_P_CurrentCharacter) MetaDefault.GetEntity(entityId);
	public static C_P_CurrentCharacter GetEntity(int index) => (C_P_CurrentCharacter) MetaDefault[index];
	public static C_P_CurrentCharacter GetEntity(string entityName) => (C_P_CurrentCharacter) MetaDefault.GetEntity(entityName);
	public static C_P_CurrentCharacter NewEntity() => (C_P_CurrentCharacter) MetaDefault.NewEntity();
	public static C_P_CurrentCharacter NewEntity(BGId entityId) => (C_P_CurrentCharacter) MetaDefault.NewEntity(entityId);
	public static C_P_CurrentCharacter NewEntity(Action<C_P_CurrentCharacter> callback) => (C_P_CurrentCharacter) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((C_P_CurrentCharacter)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5650283725877348560UL,2541090741315398062UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4664195966365923244UL, 1369876315198988210UL));
		_ufle12jhs77_F_Character = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5641411118652723440UL, 5848902406740597685UL));
		_ufle12jhs77_F_Level = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5230488391329767903UL, 13692343905593137327UL));
		_ufle12jhs77_F_Exp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldLong>(_metaDefault, new BGId(5228304755770654548UL, 6284609355131697283UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_Character = null;
		_ufle12jhs77_F_Level = null;
		_ufle12jhs77_F_Exp = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new C_P_CurrentCharacter(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new C_P_CurrentCharacter(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "P_CurrentCharacter";
		public const string name = "name";
		public const string Character = "Character";
		public const string Level = "Level";
		public const string Exp = "Exp";
	}
}

[Preserve]
public sealed partial class C_P_PlayerPrefs : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5328340787557776426UL,7208061094217622419UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4933405413978921767UL, 9327687029370969782UL), () => _ufle12jhs77_F_name = null);
	private C_P_PlayerPrefs() : base(MetaDefault) {}
	private C_P_PlayerPrefs(BGId id) : base(MetaDefault, id) {}
	private C_P_PlayerPrefs(BGMetaEntity meta) : base(meta) {}
	private C_P_PlayerPrefs(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static C_P_PlayerPrefs FindEntity(Predicate<C_P_PlayerPrefs> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<C_P_PlayerPrefs> FindEntities(Predicate<C_P_PlayerPrefs> filter, List<C_P_PlayerPrefs> result=null, Comparison<C_P_PlayerPrefs> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<C_P_PlayerPrefs> action, Predicate<C_P_PlayerPrefs> filter=null, Comparison<C_P_PlayerPrefs> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static C_P_PlayerPrefs GetEntity(BGId entityId) => (C_P_PlayerPrefs) MetaDefault.GetEntity(entityId);
	public static C_P_PlayerPrefs GetEntity(int index) => (C_P_PlayerPrefs) MetaDefault[index];
	public static C_P_PlayerPrefs GetEntity(string entityName) => (C_P_PlayerPrefs) MetaDefault.GetEntity(entityName);
	public static C_P_PlayerPrefs NewEntity() => (C_P_PlayerPrefs) MetaDefault.NewEntity();
	public static C_P_PlayerPrefs NewEntity(BGId entityId) => (C_P_PlayerPrefs) MetaDefault.NewEntity(entityId);
	public static C_P_PlayerPrefs NewEntity(Action<C_P_PlayerPrefs> callback) => (C_P_PlayerPrefs) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((C_P_PlayerPrefs)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5328340787557776426UL,7208061094217622419UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4933405413978921767UL, 9327687029370969782UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new C_P_PlayerPrefs(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new C_P_PlayerPrefs(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "P_PlayerPrefs";
		public const string name = "name";
	}
}

[Preserve]
public sealed partial class C_P_CurrentNode : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4685802224414440166UL,4655523767450569883UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4874107015740365977UL, 7887987874071323042UL), () => _ufle12jhs77_F_name = null);
	private C_P_CurrentNode() : base(MetaDefault) {}
	private C_P_CurrentNode(BGId id) : base(MetaDefault, id) {}
	private C_P_CurrentNode(BGMetaEntity meta) : base(meta) {}
	private C_P_CurrentNode(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static C_P_CurrentNode FindEntity(Predicate<C_P_CurrentNode> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<C_P_CurrentNode> FindEntities(Predicate<C_P_CurrentNode> filter, List<C_P_CurrentNode> result=null, Comparison<C_P_CurrentNode> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<C_P_CurrentNode> action, Predicate<C_P_CurrentNode> filter=null, Comparison<C_P_CurrentNode> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static C_P_CurrentNode GetEntity(BGId entityId) => (C_P_CurrentNode) MetaDefault.GetEntity(entityId);
	public static C_P_CurrentNode GetEntity(int index) => (C_P_CurrentNode) MetaDefault[index];
	public static C_P_CurrentNode GetEntity(string entityName) => (C_P_CurrentNode) MetaDefault.GetEntity(entityName);
	public static C_P_CurrentNode NewEntity() => (C_P_CurrentNode) MetaDefault.NewEntity();
	public static C_P_CurrentNode NewEntity(BGId entityId) => (C_P_CurrentNode) MetaDefault.NewEntity(entityId);
	public static C_P_CurrentNode NewEntity(Action<C_P_CurrentNode> callback) => (C_P_CurrentNode) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((C_P_CurrentNode)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4685802224414440166UL,4655523767450569883UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4874107015740365977UL, 7887987874071323042UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new C_P_CurrentNode(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new C_P_CurrentNode(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "P_CurrentNode";
		public const string name = "name";
	}
}

[Preserve]
public sealed partial class C_M_Quest : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4821112276161660914UL,7572557399160455824UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public System.String F_nameKey
	{
		get => _F_nameKey[Index];
		set => _F_nameKey[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5332830090075475571UL, 13252162662547608474UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_nameKey;
	public static BansheeGz.BGDatabase.BGFieldString _F_nameKey => _ufle12jhs77_F_nameKey ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5489567800157467292UL, 11365081526146809516UL), () => _ufle12jhs77_F_nameKey = null);
	private C_M_Quest() : base(MetaDefault) {}
	private C_M_Quest(BGId id) : base(MetaDefault, id) {}
	private C_M_Quest(BGMetaEntity meta) : base(meta) {}
	private C_M_Quest(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static C_M_Quest FindEntity(Predicate<C_M_Quest> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<C_M_Quest> FindEntities(Predicate<C_M_Quest> filter, List<C_M_Quest> result=null, Comparison<C_M_Quest> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<C_M_Quest> action, Predicate<C_M_Quest> filter=null, Comparison<C_M_Quest> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static C_M_Quest GetEntity(BGId entityId) => (C_M_Quest) MetaDefault.GetEntity(entityId);
	public static C_M_Quest GetEntity(int index) => (C_M_Quest) MetaDefault[index];
	public static C_M_Quest GetEntity(string entityName) => (C_M_Quest) MetaDefault.GetEntity(entityName);
	public static C_M_Quest NewEntity() => (C_M_Quest) MetaDefault.NewEntity();
	public static C_M_Quest NewEntity(BGId entityId) => (C_M_Quest) MetaDefault.NewEntity(entityId);
	public static C_M_Quest NewEntity(Action<C_M_Quest> callback) => (C_M_Quest) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((C_M_Quest)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4821112276161660914UL,7572557399160455824UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5332830090075475571UL, 13252162662547608474UL));
		_ufle12jhs77_F_nameKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5489567800157467292UL, 11365081526146809516UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_nameKey = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new C_M_Quest(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new C_M_Quest(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "M_Quest";
		public const string name = "name";
		public const string nameKey = "nameKey";
	}
}

[Preserve]
public static class BGCodeGenRuntimeInitializer
{
	[Preserve]
	public static void InitializeCodeGenRuntime()
	{
		C_DbPartitionVertical.InitializeCodeGenRuntime();
		C_DbPartitionVerticalMetas.InitializeCodeGenRuntime();
		C_M_Item.InitializeCodeGenRuntime();
		C_P_MapUpgrade.InitializeCodeGenRuntime();
		C_E_Event.InitializeCodeGenRuntime();
		C_M_Addressables.InitializeCodeGenRuntime();
		C_LOC_Texts.InitializeCodeGenRuntime();
		C_M_Currency.InitializeCodeGenRuntime();
		C_M_Map.InitializeCodeGenRuntime();
		C_M_Building.InitializeCodeGenRuntime();
		C_M_Character.InitializeCodeGenRuntime();
		C_P_CurrentCharacter.InitializeCodeGenRuntime();
		C_P_PlayerPrefs.InitializeCodeGenRuntime();
		C_P_CurrentNode.InitializeCodeGenRuntime();
		C_M_Quest.InitializeCodeGenRuntime();
	}
	[Preserve]
	public static void ReleaseCodeGenRuntime()
	{
		C_DbPartitionVertical.ReleaseCodeGenRuntime();
		C_DbPartitionVerticalMetas.ReleaseCodeGenRuntime();
		C_M_Item.ReleaseCodeGenRuntime();
		C_P_MapUpgrade.ReleaseCodeGenRuntime();
		C_E_Event.ReleaseCodeGenRuntime();
		C_M_Addressables.ReleaseCodeGenRuntime();
		C_LOC_Texts.ReleaseCodeGenRuntime();
		C_M_Currency.ReleaseCodeGenRuntime();
		C_M_Map.ReleaseCodeGenRuntime();
		C_M_Building.ReleaseCodeGenRuntime();
		C_M_Character.ReleaseCodeGenRuntime();
		C_P_CurrentCharacter.ReleaseCodeGenRuntime();
		C_P_PlayerPrefs.ReleaseCodeGenRuntime();
		C_P_CurrentNode.ReleaseCodeGenRuntime();
		C_M_Quest.ReleaseCodeGenRuntime();
	}
}
#pragma warning restore 414
